spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:mariadb://192.168.1.253:3306/testdb;
        driver-class-name: org.mariadb.jdbc.Driver
        username: sa
        password: sa
    jpa:
        database-platform: org.hibernate.dialect.mariadb53dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                show-sql: true
                format-sql: true
        hibernate:
            ddl-auto: create-drop